"""Add agent tasks and dom cache

Revision ID: 1082140833d3
Revises: 513c7a54e454
Create Date: 2026-07-10 22:51:48.092431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1082140833d3'
down_revision: Union[str, Sequence[str], None] = '513c7a54e454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_dom_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_domain', sa.String(length=255), nullable=False),
    sa.Column('dom_structure_hash', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_dom_cache_dom_structure_hash'), 'resource_dom_cache', ['dom_structure_hash'], unique=False)
    op.create_index(op.f('ix_resource_dom_cache_resource_domain'), 'resource_dom_cache', ['resource_domain'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_owner_id'), 'agent_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('agent_task_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_task_events_task_id'), 'agent_task_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_task_events_task_id'), table_name='agent_task_events')
    op.drop_table('agent_task_events')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_owner_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_resource_dom_cache_resource_domain'), table_name='resource_dom_cache')
    op.drop_index(op.f('ix_resource_dom_cache_dom_structure_hash'), table_name='resource_dom_cache')
    op.drop_table('resource_dom_cache')
    # ### end Alembic commands ###
