"""Contextus 2.0 Sprint 3 Models

Revision ID: 1b2accbd82e2
Revises: 1082140833d3
Create Date: 2026-07-12 21:40:53.584189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2accbd82e2'
down_revision: Union[str, Sequence[str], None] = '1082140833d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('tps', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('actions_log', sa.Text(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_traces_session_id'), 'execution_traces', ['session_id'], unique=False)
    op.create_table('agent_subtasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('depends_on_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('prompt_instruction', sa.Text(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_output', sa.Text(), nullable=True),
    sa.Column('dom_cache_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_id'], ['agent_subtasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_subtasks_status'), 'agent_subtasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_subtasks_task_id'), 'agent_subtasks', ['task_id'], unique=False)
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), server_default='Task', nullable=False))
        batch_op.add_column(sa.Column('cron_expression', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('training_mode', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_column('training_mode')
        batch_op.drop_column('cron_expression')
        batch_op.drop_column('title')
    op.drop_index(op.f('ix_agent_subtasks_task_id'), table_name='agent_subtasks')
    op.drop_index(op.f('ix_agent_subtasks_status'), table_name='agent_subtasks')
    op.drop_table('agent_subtasks')
    op.drop_index(op.f('ix_execution_traces_session_id'), table_name='execution_traces')
    op.drop_table('execution_traces')
    # ### end Alembic commands ###
