"""Add hashing to ScenarioDefinition

Revision ID: 30c333b725fc
Revises: 938b31f74b1f
Create Date: 2026-07-24 16:30:54.528014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c333b725fc'
down_revision: Union[str, Sequence[str], None] = '938b31f74b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_hash', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scenario_definitions_scenario_hash'), ['scenario_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_definitions_scenario_hash'))
        batch_op.drop_column('approved_hash')
        batch_op.drop_column('scenario_hash')

    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
