"""add_uq_conv_tg_chat_and_login_tokens

Revision ID: 39ffa5119abc
Revises: d34a5f0bb1f1
Create Date: 2026-09-17 20:01:31.076366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ffa5119abc'
down_revision: Union[str, Sequence[str], None] = 'd34a5f0bb1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_conversation_telegram_chat_id', ['telegram_chat_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('login_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('login_token_expires')
        batch_op.drop_column('login_token')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_conversation_telegram_chat_id', type_='unique')

    # ### end Alembic commands ###
