"""add_tool_verification

Revision ID: 6e43d9d8e940
Revises: 8c01d3ae0a52
Create Date: 2026-07-14 17:08:43.820495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e43d9d8e940'
down_revision: Union[str, Sequence[str], None] = '8c01d3ae0a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tool_verification_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.drop_column('tool_verification_details')
        batch_op.drop_column('tool_verified')

    # ### end Alembic commands ###
