"""Add analytics fields

Revision ID: 8c01d3ae0a52
Revises: 1b2accbd82e2
Create Date: 2026-07-14 01:39:44.864109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c01d3ae0a52'
down_revision: Union[str, Sequence[str], None] = '1b2accbd82e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('correction_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_corrections_task_id'), 'human_corrections', ['task_id'], unique=False)
    op.add_column('execution_traces', sa.Column('task_id', sa.String(length=36), nullable=True))
    op.add_column('execution_traces', sa.Column('task_type_classified', sa.String(length=50), nullable=True))
    op.add_column('execution_traces', sa.Column('task_type_final', sa.String(length=50), nullable=True))
    op.add_column('execution_traces', sa.Column('model_selected', sa.String(length=100), nullable=True))
    op.add_column('execution_traces', sa.Column('planner_enabled', sa.Boolean(), nullable=True))
    op.add_column('execution_traces', sa.Column('tools_available', sa.Integer(), nullable=True))
    op.add_column('execution_traces', sa.Column('tools_called', sa.Integer(), nullable=True))
    op.add_column('execution_traces', sa.Column('tools_called_names', sa.Text(), nullable=True))
    op.add_column('execution_traces', sa.Column('stage_durations', sa.Text(), nullable=True))
    op.add_column('execution_traces', sa.Column('final_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_execution_traces_final_status'), 'execution_traces', ['final_status'], unique=False)
    op.create_index(op.f('ix_execution_traces_model_selected'), 'execution_traces', ['model_selected'], unique=False)
    op.create_index(op.f('ix_execution_traces_task_id'), 'execution_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_task_type_classified'), 'execution_traces', ['task_type_classified'], unique=False)
    op.create_foreign_key(None, 'execution_traces', 'agent_tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution_traces', type_='foreignkey')
    op.drop_index(op.f('ix_execution_traces_task_type_classified'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_task_id'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_model_selected'), table_name='execution_traces')
    op.drop_index(op.f('ix_execution_traces_final_status'), table_name='execution_traces')
    op.drop_column('execution_traces', 'final_status')
    op.drop_column('execution_traces', 'stage_durations')
    op.drop_column('execution_traces', 'tools_called_names')
    op.drop_column('execution_traces', 'tools_called')
    op.drop_column('execution_traces', 'tools_available')
    op.drop_column('execution_traces', 'planner_enabled')
    op.drop_column('execution_traces', 'model_selected')
    op.drop_column('execution_traces', 'task_type_final')
    op.drop_column('execution_traces', 'task_type_classified')
    op.drop_column('execution_traces', 'task_id')
    op.drop_index(op.f('ix_human_corrections_task_id'), table_name='human_corrections')
    op.drop_table('human_corrections')
    # ### end Alembic commands ###
