"""Add ApprenticeStep and ScenarioDefinition

Revision ID: 938b31f74b1f
Revises: 2513313de1c4
Create Date: 2026-07-19 18:25:44.965024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938b31f74b1f'
down_revision: Union[str, Sequence[str], None] = '2513313de1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apprentice_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('proposed_tool', sa.String(), nullable=True),
    sa.Column('proposed_args', sa.Text(), nullable=True),
    sa.Column('proposed_reasoning', sa.Text(), nullable=True),
    sa.Column('proposed_response_text', sa.Text(), nullable=True),
    sa.Column('human_decision', sa.String(), nullable=True),
    sa.Column('corrected_args', sa.Text(), nullable=True),
    sa.Column('corrected_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('proposed_by_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
