"""add_user_auditlog_tg_sync

Revision ID: d34a5f0bb1f1
Revises: fc65b3534b78
Create Date: 2026-09-17 16:10:24.247105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34a5f0bb1f1'
down_revision: Union[str, Sequence[str], None] = 'fc65b3534b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('linking_token', sa.String(length=64), nullable=True),
    sa.Column('linking_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    # Seed: создаём начального админа из env
    import os
    initial_admin_tg = os.getenv("INITIAL_ADMIN_TELEGRAM_ID") or os.getenv("ALLOWED_TELEGRAM_USER_ID")
    if initial_admin_tg:
        users_table = sa.table('users',
            sa.column('role', sa.String),
            sa.column('telegram_chat_id', sa.String),
            sa.column('display_name', sa.String),
        )
        op.bulk_insert(users_table, [
            {"role": "admin", "telegram_chat_id": str(initial_admin_tg), "display_name": "Initial Admin"}
        ])

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_telegram_chat_id'), ['telegram_chat_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_execution_traces_task_id_tasks', 'agent_tasks', ['task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_status'), ['status'], unique=False)

    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_execution_traces_task_id_tasks', type_='foreignkey')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_telegram_chat_id'))
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('user_id')

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
